# linuxkit build template 
#
# Copyright (c) 2018 Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0
org: lfedge
image: eve-pillar
network: yes
config:
  binds:
    - /lib/modules:/lib/modules
    - /dev:/dev
    - /etc/resolv.conf:/etc/resolv.conf
    - /run:/run
    - /config:/config
    - /:/hostfs
    - /persist:/persist:rshared,rbind
  net: host
  capabilities:
    - all
  security_opt:
    - seccomp:unconfined
  ports:
    - 2345:2345
  pid: host
  rootfsPropagation: shared
